### ISSUE TITLE
Dealing With Overflow Inside J

### ISSUE THREAD

**Issue by andydmh** [andydmh/Machine-Learning-Group9#12]
While training, that is when the method fit is called and it has to deal with big x values the function J overflows at the beginning of the training when theta has small values and the difference between the expected and the predicted value is huge. It seems to be a common problem. We may need to read a bit about how to fix this issue.

**Comment by jbowren** [comment]
It looks like the basis functions for the data is simply the identity phi(x) = x. This way the error will only increase monotonically with larger and larger values of x. I think the way to get around this is to use some bounded function like the logistic function.

That being said, I am not sure we really have to worry about this; I don't think the housing price dataset has extremely large values.

**Comment by andydmh** [comment]
The overflow happens when calculating the sum of each dot product of theta and each x_i which belongs to matrix X. This happens specially when the batch size is big that is the sum goes from 1 to n where n is a large number. Really there is nothing that can be done on the case of big batch sizes other than reducing the size of element of x_i (individual features) by doing something like max normalization on the entire column of the feature. The problem will defiantly be avoided when doing SGD which deals with one x_i example at the time to make theta parameters updates.
