### ISSUE TITLE
Find a dataset for logistic regression

### ISSUE THREAD

**Issue by vperidot** [andydmh/Machine-Learning-Group9#16]
Logistic regression tackles the problem of classification, both binary and multinomial. We need a data set that lends itself to a logistic regression.

**Comment by vperidot** [comment]
One possibility for a binary classification would be this voter survey dataset:
https://www.kaggle.com/democracy-fund/2016-voter-survey/data
we could attempt to predict whether or not a respondent voted in the 2016 election.

**Comment by andydmh** [comment]
Easy binary classification data to load: 

Sentiment Classification (applied to movies):
[IMDB Movie Reviews Sentiment Classification From Keras](https://keras.io/datasets/#imdb-movie-reviews-sentiment-classification)
 

Breast Cancer Dataset:
[How To Load Breast Cancer Dataset With Skit-Learn](http://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_breast_cancer.html)

**Comment by andydmh** [comment]
The IMDB dataset is too big to be handled by BGD. We already have the Breast Cancer dataset working but if you are interesting on adding a more complex/interesting dataset these are some great options [Classification Datasets](https://archive.ics.uci.edu/ml/datasets.html?format=&task=cla&att=&area=&numAtt=&numIns=&type=&sort=nameUp&view=list). It is pretty simple to add a new dataset to our code once the function to load it is implemented. Look at examples on run.py.
