### ISSUE TITLE
Generate Simple Data For Testing

### ISSUE THREAD

**Issue by andydmh** [andydmh/Machine-Learning-Group9#18]
Implement function genPolyRandomDataClass on the data.py file line 12.

**Comment by jbowren** [comment]
I need this method for testing. @Jagruteep if you're having trouble, please reach out to us.

**Comment by andydmh** [comment]
genPolyRandomDataClass is already implemented. Look at an example of how to call the function on test.py. Pretty much just call genPolyRandomDataClass with the number of points you want to generate. For example genPolyRandomDataClass(100) for 100 points. The function will return X,y where y_i belongs to {0,1} and y contains 100 elements. X is a 2 dimensional numpy array (a matrix) where each row contains 2 elements x_1 and x_2 were x_1 and x_2 are continuos values and there are a total of 100 rows. These variables theta1=2, theta2=4, mu=0, sigma=5 are predefined but you can also modify them by passing different values as parameters of genPolyRandomDataClass. If the method is fine it should recover values close to the original theta1 and theta2 with which the data was generated.
