### ISSUE TITLE
Select Dataset For Regression

### ISSUE THREAD

**Issue by andydmh** [andydmh/Machine-Learning-Group9#2]
Come up with datasets we want to use.
Here are some links of dataset repositories:

1. [UCI](https://archive.ics.uci.edu/ml/datasets.html)

2. [Kaggle](https://www.kaggle.com/datasets)

Comment bellow any specific dataset that you will prefer to use for regression.

**Comment by andydmh** [comment]
[House Price Prediction](https://www.kaggle.com/c/house-prices-advanced-regression-techniques/data)

**Comment by andydmh** [comment]
This is a set of Regression datasets:
[UCI Regression datasets](https://archive.ics.uci.edu/ml/datasets.html?format=&task=reg&att=&area=&numAtt=&numIns=&type=&sort=nameUp&view=table)

**Comment by jbowren** [comment]
I like the housing price dataset (Ames Housing Dataset).

**Comment by Jagruteep** [comment]
Yes, Housing Price Prediction Dataset !

**Comment by andydmh** [comment]
The probably we should start working on loading and preparing the data on the Ames Housing Dataset. Lets debate that today after class.
