### ISSUE TITLE
Load Data

### ISSUE THREAD

**Issue by andydmh** [andydmh/Machine-Learning-Group9#9]
After we decide which dataset to use we need to read the data into an X matrix which consist of xi vectors of features and y vectors of of expected outputs. This function should be implemented inside the data.py file

**Comment by andydmh** [comment]
One of the issues with the dataset is that they are not providing y values (SalePrice) for test data (test.csv). Kaggle does this because since it is a competition we are just suppose to upload results (our SalePrice prediction) and they do the evaluation. This will not work for us, we need the actual y_values of test in order to compare our model with others. What we can do is to just load the file train.scv which do contain SalePrice and spliced latter on train, validation and test (there is already a function built to split the data once it is loaded in the correct format). I created a function interface called loadHouseData to be implemented in order to load the data.

**Comment by jbowren** [comment]
I wrote some code to extract the first n integers for every house. I believe you said the matrix X should be a 2D numpy array where each column is a training example. Is this correct?

**Comment by andydmh** [comment]
@jbowren yes that is correct. X = [x1, x2, x3, ..., xn] where n is the number of rows and each xi = [f1, f2, f3, ..., fm] where m is the number of features/columns on the table (of course all the columns except for the SalePrice which is the y value). y = [y1, y2, ..., yn] where each yi is the SalePrice of the house described by the features on xi. Example: If X belongs to R^(2,3) that means there are 2 rows and each row has 3 features. Also for reference use genPolyRandomDataReg function inside data.py. The function loading the data from the dataset should do something similar and return X, y as well.

**Comment by andydmh** [comment]
Although some improvement in performance can be observed by using the current 5 features, it is not that good. The model struggles during training to find a relation with those 5 features. It will be much better if more features are extracted.

**Comment by andydmh** [comment]
Sounds good @vperidot when you get it to work can you please test it using runHousePriceExperimentBGD function inside run.py by loading your data on line 27. Also make sure you change the experiment name "'HousePricingPrediction'" on line 187 to create a new directory and avoid rewriting our current results (even if they are not that good) for comparison purpose. Also notice that if you do not comment out or change the experiment names on lines 190 and line 194 the directories with the experiments on the other 2 datasets will be rewritten.

**Comment by andydmh** [comment]
@vperidot @jbowren @Jagruteep also if you want to load a different dataset it is fine as long as you extract the data in the correct format described before (X,y) it will be easy to train with the data (look at how to do it inside run.py). Also if you want to implement a different model you can do it inside model.py by creating a new class that inherits from Model (use LinearRegressionModel as an example). Also Batch Gradient Descent is working fine but there is an issue with SGD (the weights are not being updated correctly) if anyone can play with the code and figure it out the issue it will be great (we already have one regression model but if we figure that out, we will have 2) I think the issue is on model.py line 90 but I may be wrong (the math is described on [Supervised Learning by Andrew Ng](http://cs229.stanford.edu/notes/cs229-notes1.pdf))
